### ISSUE TITLE
NLG in Spanish

### ISSUE THREAD

**Issue by alexol91** [roman-kutlak/nlglib#6]
I am starting a PhD in NLG in Spanish. I've seen your library and I think that it is very interesting. I would like to have more detailed documentation. And if you think it's a good idea, help improve your performance in Spanish.

**Comment by alexol91** [comment]
You are generating sentences like:
La **niño** **habe estado** dando regalos muy rápido.
instead of:
La **niña ha estado** dando regalos muy rápido.

Code Example:
`subject = NP('el','niño',features={GENDER.feminine})`
`predicate = VP('dar', features={ASPECT.perfect_progressive, TENSE.past, })`

**Comment by roman-kutlak** [comment]
Hi! I am glad you want to help with NLG, but this project is probably not the right one. The reason for it is that `nlglib` is essentially a wrapper around another library, which does the surface realisation: [SimpleNLG](https://github.com/simplenlg/simplenlg). The project you want to look at is the Spanish version of SimpleNLG: [SimpleNLG-ES](https://github.com/citiususc/SimpleNLG-ES). That is the part which is actually creating the sentences. Happy to answer any more questions about this -- just leave them below.

Best,
Roman
