### ISSUE TITLE
AdverbPhrase method name inconsistency in visitors.ReprVisitor

### ISSUE THREAD

**Issue by KeshiChen** [roman-kutlak/nlglib#7]
Method name should be adverb_phrase, instead of advp.
It causes arrtibute not found error when calling AdverbPhrase() method

**Comment by KeshiChen** [comment]
Error Message: 'ReprVisitor' object has no attribute 'adverb_phrase'

**Comment by roman-kutlak** [comment]
Hi, thanks for reporting this and for the PR. I have merged it and will try to update pypi over the weekend.
